name: mhions
favicon: null
layout_spectrum: 0.966097995871678
typography_spectrum: 0.8348663260694593
title: mh ions by Matthias Halibrand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6856765989214182
  lightness: 0.8407687018625438
  saturation: 0.0783998214174062
  rhythmicContrast: 0.7771573492791504
purpose: []
