name: mh ions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41249
title: mh ions by Matthias Halibrand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#808080'
    - '#a4a4a4'
    - '#4a3a3c'
    - '#7cc3c0'
  brandStrength: 0
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
